Workflow:
  '@WorkflowId': '{8131387f-61f6-ef11-9341-7c1e52168ba1}'
  '@Name': A flow
  JsonFileName: /modernflows/8131387f-61f6-ef11-9341-7c1e52168ba1/Aflow-8131387F-61F6-EF11-9341-7C1E52168BA1.json
  Type: 1
  Subprocess: 0
  Category: 5
  Mode: 0
  Scope: 4
  OnDemand: 0
  TriggerOnCreate: 0
  TriggerOnDelete: 0
  AsyncAutodelete: 0
  SyncWorkflowLogOnFailure: 0
  StateCode: 1
  StatusCode: 2
  RunAs: 1
  IsTransacted: 1
  IntroducedVersion: 1.0.0.0
  IsCustomizable: 1
  BusinessProcessType: 0
  IsCustomProcessingStepAllowedForOtherPublishers: 1
  PrimaryEntity: none
  LocalizedNames:
    LocalizedName:
      '@languagecode': 1033
      '@description': A flow
